name : test_workflow
on : 
    push:
        branches:
            - main
jobs:
    jobs_1:
        name: my_first_job
        runs-on: ubuntu-latest
        steps:
            - name: success
              run: echo "this was successful, well done!!"